
import copy
import json

# Reference for valid fields and full names
valid_fields = {
    'acc-no': 'Account No.',
    'clinician-no': 'Clinician No.',
    'pt-no': 'Patient No.',
    'pt-first-name': 'Patient First Name',
    'pt-middle-name': 'Patient Middle Name',
    'pt-last-name': 'Patient Last Name',
    'pt-gender': 'Patient Gender',
    'pt-dob': 'Patient DOB',
    'pt-weight': 'Patient Weight',
    'pt-shoe-size': 'Patient Shoe Size',
    'pt-foot-size': 'Patient Foot Size',
    'pt-outgrowth': 'Patient Outgrowth',
    'foot-impression': 'Foot Impression',
    'aoms-scan-type': 'AOMS Scan Type',
    'foot-to-scan': 'Foot to Scan',
    'priority': 'Priority',
    'due-date': 'Due Date',
    'po-no': 'PO#',
    'alt-address': 'Alternate Address',
    'alt-code': 'Alternate Code',
    'alt-name': 'Alternate Name',
    'alt-civic-address': 'Alternate Civic Address',
    'alt-noncivic-address': 'Alternate Non Civic Address',
    'alt-additional-address': 'Alternate Additional Address',
    'alt-city': 'Alternate City',
    'alt-province-state': 'Alternate Province State',
    'alt-postal-zip-code': 'Alternate Postal Zip Code',
    'alt-country-code': 'Alternate Country Code',
    'alt-phone-no': 'Alternate Phone No',
    'alt-contact': 'Alternate Contact',
    'alt-location-code': 'Alternate Location Code',
    'alt-ship-method-code': 'Alternate Shipment Method Code',
    'alt-ship-agent-code': 'Alternate Shipping Agent Code',
    'ship -with-sales-order': 'Ship with Sales Order',
    'lfe-wo-no': 'Use Scan from LFE WO#',
    'lfe-duplicate-changed': 'Duplicate or Change LFE order',
    'am-wo-no': 'Use Scan from AM WO#',
    'am-duplicate-changed': 'Duplicate or Change AM order',
    'device-code': 'Lab Device Code',
    'quantity': 'Quantity',
    'quantity-uom': 'Quantity UOM',
    'heel-cup-depth_b': 'Heel Cup Depth - Bilateral',
    'heel-cup-depth_l': 'Heel Cup Depth - Left',
    'heel-cup-depth_r': 'Heel Cup Depth - Right',
    '1st-met-cut-out_b': '1st Met Cut Out - Bilateral',
    '1st-met-cut-out_l': '1st Met Cut Out - Left',
    '1st-met-cut-out_r': '1st Met Cut Out - Right',
    '1st-ray-cut-out_b': '1st Ray Cut Out - Bilateral',
    '1st-ray-cut-out_l': '1st Ray Cut Out - Left',
    '1st-ray-cut-out_r': '1st Ray Cut Out - Right',
    'fascial-accom_b': 'Fascial Accommodation - Bilateral',
    'fascial-accom_l': 'Fascial Accommodation - Left',
    'fasical-accom_r': 'Fascial Accommodation - Right',
    'med-flange_b': 'Medial Flange - Bilateral',
    'med-flange_l': 'Medial Flange - Left',
    'med-flange_r': 'Medial Flange - Right',
    'lat-flange_b': 'Lateral Flange - Bilateral',
    'lat-flange_l': 'Lateral Flange - Left',
    'lat-flange_r': 'Lateral Flange - Right',
    'sweet-spot-accom_b': 'Sweet Spot Accommodation - Bilateral',
    'sweet-spot-accom_l': 'Sweet Spot Accommodation - Left',
    'sweet-spot-accom_r': 'Sweet Spot Accommodation - Right',
    'heel-spur-accom_b': 'Heel Spur Accommodation - Bilateral',
    'heel-spur-accom_l': 'Heel Spur Accommodation - Left',
    'heel-spur-accom_r': 'Heel Spur Accommodation - Right',
    'heel-hole_b': 'Heel Hole - Bilateral',
    'heel-hole_l': 'Heel Hole - Left',
    'heel-hole_r': 'Heel Hole - Right',
    'rigid-1st-ext_b': 'Rigid 1st Extension - Bilateral',
    'rigid-1st-ext_l': 'Rigid 1st Extension - Left',
    'rigid-1st-ext_r': 'Rigid 1st Extension - Right',
    'orth-width_b': 'Orthotic Width - Bilateral',
    'orth-width_l': 'Orthotic Width - Left',
    'orth-width_r': 'Orthotic Width - Right',
    'gait_b': 'Gait - Bilateral',
    'gait_l': 'Gait - Left',
    'gait_r': 'Gait - Right',
    'shell-code_b': 'Shell Code - Bilateral',
    'shell-code_l': 'Shell Code - Left',
    'shell-code_r': 'Shell Code - Right',
    'fill-code_b': 'Fill Code - Bilateral',
    'fill-type_b': 'Fill Type - Bilateral',
    'fill-code_l': 'Fill Code - Left',
    'fill-type_l': 'Fill Type - Left',
    'fill-code_r': 'Fill Code - Right',
    'fill-type_r': 'Fill Type - Right',
    'ext-code_b': 'Extension Code - Bilateral',
    'ext-length_b': 'Extension Length - Bilateral',
    'ext-sp-code_b': 'Extension Specific Code - Bilateral',
    'ext-code_l': 'Extension Code - Left',
    'ext-length_l': 'Extension Length - Left',
    'ext-sp-code_l': 'Extension Specific Code - Left',
    'ext-code_r': 'Extension Code - Right',
    'ext-length_r': 'Extension Length - Right',
    'ext-sp-code_r': 'Extension Specific Code - Right',
    'tc1-code_b': 'Top Cover# 1 Code - Bilateral',
    'tc1-length_b': 'Top Cover# 1 Length - Bilateral',
    'tc1-code_l': 'Top Cover# 1 Code - Left',
    'tc1-length_l': 'Top Cover# 1 Length - Left',
    'tc1-code_r': 'Top Cover# 1 Code - Right',
    'tc1-length_r': 'Top Cover# 1 Length - Right',
    'tc2-code_b': 'Top Cover# 2 Code - Bilateral',
    'tc2-length_b': 'Top Cover# 2 Length - Bilateral',
    'tc2-code_l': 'Top Cover# 2 Code - Left',
    'tc2-length_l': 'Top Cover# 2 Length - Left',
    'tc2-code_r': 'Top Cover# 2 Code - Right',
    'tc2-length_r': 'Top Cover# 2 Length - Right',
    'tc3-code_b': 'Top Cover# 3 Code - Bilateral',
    'tc3-length_b': 'Top Cover# 3 Length - Bilateral',
    'tc3-code_l': 'Top Cover# 3 Code - Left',
    'tc3-length_l': 'Top Cover# 3 Length - Left',
    'tc3-code_r': 'Top Cover# 3 Code - Right',
    'tc3-length_r': 'Top Cover# 3 Length - Right',
    'bc-code_b': 'Bottom Cover Code - Bilateral',
    'bc-length_b': 'Bottom Cover Length - Bilateral',
    'bc-code_l': 'Bottom Cover Code - Left',
    'bc-length_l': 'Bottom Cover Length - Left',
    'bc-code_r': 'Bottom Cover Code - Right',
    'bc-length_r': 'Bottom Cover Length - Right',
    'rf-post-code_b': 'Rearfoot Post Code - Bilateral',
    'rf-post-type_b': 'Rearfoot Post Type - Bilateral',
    'rf-post-code_l': 'Rearfoot Post Code - Left',
    'rf-post-type_l': 'Rearfoot Post Type - Left',
    'rf-post-code_r': 'Rearfoot Post Code - Right',
    'rf-post-type_r': 'Rearfoot Post Type - Right',
    'strikeplate-code_b': 'Strikeplate Code - Bilateral',
    'strikeplate-code_l': 'Strikeplate Code - Left',
    'strikeplate-code_r': 'Strikeplate Code - Right',
    'ff-post-code_b': 'Forefoot Post Code - Bilateral',
    'ff-post-type_b': 'Forefoot Post Type - Bilateral',
    'ff-post-sp-code_b': 'Forefoot Post Specific Code - Bilateral',
    'ff-post-code_l': 'Forefoot Post Code - Left',
    'ff-post-type_l': 'Forefoot Post Type - Left',
    'ff-post-sp-code_l': 'Forefoot Post Specific Code - Left',
    'ff-post-code_r': 'Forefoot Post Code - Right',
    'ff-post-type_r': 'Forefoot Post Type - Right',
    'ff-post-sp-code_r': 'Forefoot Post Specific Code - Right',
    'add1-code_b': 'Addition# 1 Code - Bilateral',
    'add1-code_l': 'Addition# 1 Code - Left',
    'add1-code_r': 'Addition# 1 Code - Right',
    'add2-code_b': 'Addition# 2 Code - Bilateral',
    'add2-code_l': 'Addition# 2 Code - Left',
    'add2-code_r': 'Addition# 2 Code - Right',
    'add3-code_b': 'Addition# 3 Code - Bilateral',
    'add3-code_l': 'Addition# 3 Code - Left',
    'add3-code_r': 'Addition# 3 Code - Right',
    'heel-lift-code_b': 'Addition Heel Lift Code - Bilateral',
    'heel-lift-length_b': 'Addition Heel Lift Length - Bilateral',
    'heel-lift-sp-code_b': 'Addition Heel Lift Specific Code - Bilateral',
    'heel-lift-code_l': 'Addition Heel Lift Code - Left',
    'heel-lift-length_l': 'Addition Heel Lift Length - Left',
    'heel-lift-sp-code_l': 'Addition Heel Lift Specific Code - Left',
    'heel-lift-code_r': 'Addition Heel Lift Code - Right',
    'heel-lift-length_r': 'Addition Heel Lift Length - Right',
    'heel-lift-sp-code_r': 'Addition Heel Lift Specific Code - Right',
    'posting-position_b': 'Posting Position - Bilateral',
    'posting-position_l': 'Posting Position - Left',
    'posting-position_r': 'Posting Position - Right',
    'corr-type_b': 'Corrections Type - Bilateral',
    'corr-type_l': 'Corrections Type - Left',
    'corr-type_r': 'Corrections Type - Right',
    'skive_b': 'Skive - Bilateral',
    'skive-uom_b': 'Skive UOM - Bilateral',
    'skive_l': 'Skive - Left',
    'skive-uom_l': 'Skive UOM - Left',
    'skive_r': 'Skive - Right',
    'skive-uom_r': 'Skive UOM - Right',
    'inver-ever_b': 'Inversion / Eversion - Bilateral',
    'inver-ever-uom_b': 'Inversion / Eversion UOM - Bilateral',
    'inver-ever_l': 'Inversion / Eversion - Left',
    'inver-ever-uom_l': 'Inversion / Eversion UOM - Left',
    'inver-ever_r': 'Inversion / Eversion - Right',
    'inver-ever-uom_r': 'Inversion / Eversion UOM - Right',
    'rf-ex-angle_b': 'Rearfoot Extrinsic Angle - Bilateral',
    'rf-ex-angle-uom_b': 'Rearfoot Extrinsic Angle UOM - Bilateral',
    'rf-ex-angle_l': 'Rearfoot Extrinsic Angle - Left',
    'rf-ex-angle-uom_l': 'Rearfoot Extrinsic Angle UOM - Left',
    'rf-ex-angle_r': 'Rearfoot Extrinsic Angle - Right',
    'rf-ex-angle-uom_r': 'Rearfoot Extrinsic Angle UOM - Right',
    'ff-ex-angle_b': 'Forefoot Extrinsic Angle - Bilateral',
    'ff-ex-angle-uom_b': 'Forefoot Extrinsic Angle UOM - Bilateral',
    'ff-ex-angle_l': 'Forefoot Extrinsic Angle - Left',
    'ff-ex-angle-uom_l': 'Forefoot Extrinsic Angle UOM - Left',
    'ff-ex-angle_r': 'Forefoot Extrinsic Angle - Right',
    'ff-ex-angle-uom_r': 'Forefoot Extrinsic Angle UOM - Right',
    'rf-post-type': 'Rearfoot Post Type',
    'ff-post-type': 'Forefoot Post Type',
    'motion': 'Motion'
}

tree_lines = [
'PSO > General Order Info > Account No. > acc-no',
'PSO > General Order Info > Clinician No. > clinician-no',
'PSO > General Order Info > Patient No. > pt-no',
'Patient Card > General > First Name > pt-first-name',
'Patient Card > General > Middle Name > pt-middle-name',
'Patient Card > General > Last Name > pt-last-name',
'Patient Card > General > Gender > pt-gender',
'Patient Card > General > Date of Birth > pt-dob',
'Patient Card > General > Weight > pt-weight',
'Patient Card > General > Shoe Size > pt-shoe-size',
'Patient Card > General > Foot Size > pt-foot-size',
'Patient Card > General > Outgrowth > pt-outgrowth',
'PSO > General Order Info > Foot Impression > Foot Impression > foot-impression',
'PSO > General Order Info > Aoms Scan Type > aoms-scan-type',
'PSO > General Order Info > Foot Impression > Foot to Scan > foot-to-scan',
'PSO > General Order Info > Status > Priority > priority',
'PSO > General Order Info > Status > Due Date > due-date',
'PSO > General Order Info > Status > PO# > po-no',
'PSO > General Order Info > Shipping Options > Alternate Address > alt-address',
'PSO > General Order Info > Ship-to Address Card > General > Code > alt-code',
'PSO > General Order Info > Ship-to Address Card > General >  Name > alt-name',
'PSO > General Order Info > Ship-to Address Card > General > Civic Address > alt-civic-address',
'PSO > General Order Info > Ship-to Address Card > General > Non Civic Address > alt-noncivic-address',
'PSO > General Order Info > Ship-to Address Card > General > Additional Address > alt-additional-address',
'PSO > General Order Info > Ship-to Address Card > General > City > alt-city',
'PSO > General Order Info > Ship-to Address Card > General > Province/State > alt-province-state',
'PSO > General Order Info > Ship-to Address Card > General > Postal/ZIP Code > alt-postal-zip-code',
'PSO > General Order Info > Ship-to Address Card > General > Country/Region Code > alt-country-code',
'PSO > General Order Info > Ship-to Address Card > General > Phone No > alt-phone-no',
'PSO > General Order Info > Ship-to Address Card > General > Contact > alt-contact',
'PSO > General Order Info > Ship-to Address Card > General > Location Code > alt-location-code',
'PSO > General Order Info > Ship-to Address Card > General > Shipment Method Code > alt-ship-method-code',
'PSO > General Order Info > Ship-to Address Card > General > Shipping Agent Code > alt-ship-agent-code',
'PSO > General Order Info > Shipping Options > Ship with Sales Order > ship-with-sales-order',
'PSO > Device and Shell Modifications > Subsequent Pair from LFE WO# > lfe-wo-no',
'PSO > Device and Shell Modifications > LFE Duplicate/Changed Device > lfe-duplicate-changed',
'PSO > Device and Shell Modifications > Subsequent Pair from AM WO# > am-wo-no',
'PSO > Device and Shell Modifications > AM Duplicate Device, AM Changed Device > am-duplicate-changed',
'PSO > Device and Shell Modifications > Lab Device > Item No > device-code',
'PSO > Device and Shell Modifications > Quantity > quantity',
'PSO > Device and Shell Modifications > Quantity UOM > quantity-uom',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Cup Depth > heel-cup-depth_b',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Cup Depth > heel-cup-depth_l',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Cup Depth > heel-cup-depth_r',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Met Cut Out > 1st-met-cut-out_b',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Met Cut Out > 1st-met-cut-out_l',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Met Cut Out > 1st-met-cut-out_r',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Ray Cut Out > 1st-ray-cut-out_b',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Ray Cut Out > 1st-ray-cut-out_l',
'PSO > Device and Shell Modifications > Shell Modifications > 1st Ray Cut Out > 1st-ray-cut-out_r',
'PSO > Device and Shell Modifications > Shell Modifications > Fascial Accommodation > fascial-accom_b',
'PSO > Device and Shell Modifications > Shell Modifications > Fascial Accommodation > fascial-accom_l',
'PSO > Device and Shell Modifications > Shell Modifications > Fascial Accommodation > fasical-accom_r',
'PSO > Device and Shell Modifications > Shell Modifications > Medial Flange > med-flange_b',
'PSO > Device and Shell Modifications > Shell Modifications > Medial Flange > med-flange_l',
'PSO > Device and Shell Modifications > Shell Modifications > Medial Flange > med-flange_r',
'PSO > Device and Shell Modifications > Shell Modifications > Lateral Flange > lat-flange_b',
'PSO > Device and Shell Modifications > Shell Modifications > Lateral Flange > lat-flange_l',
'PSO > Device and Shell Modifications > Shell Modifications > Lateral Flange > lat-flange_r',
'PSO > Device and Shell Modifications > Shell Modifications > Sweet Spot Accommodation > sweet-spot-accom_b',
'PSO > Device and Shell Modifications > Shell Modifications > Sweet Spot Accommodation > sweet-spot-accom_l',
'PSO > Device and Shell Modifications > Shell Modifications > Sweet Spot Accommodation > sweet-spot-accom_r',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Spur Accommodation > heel-spur-accom_b',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Spur Accommodation > heel-spur-accom_l',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Spur Accommodation > heel-spur-accom_r',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Hole > heel-hole_b',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Hole > heel-hole_l',
'PSO > Device and Shell Modifications > Shell Modifications > Heel Hole > heel-hole_r',
'PSO > Device and Shell Modifications > Shell Modifications > Rigid 1st Extension > rigid-1st-ext_b',
'PSO > Device and Shell Modifications > Shell Modifications > Rigid 1st Extension > rigid-1st-ext_l',
'PSO > Device and Shell Modifications > Shell Modifications > Rigid 1st Extension > rigid-1st-ext_r',
'PSO > Device and Shell Modifications > Shell Modifications > Orthotic Width > orth-width_b',
'PSO > Device and Shell Modifications > Shell Modifications > Orthotic Width > orth-width_l',
'PSO > Device and Shell Modifications > Shell Modifications > Orthotic Width > orth-width_r',
'PSO > Device and Shell Modifications > Shell Modifications > Gait > gait_b',
'PSO > Device and Shell Modifications > Shell Modifications > Gait > gait_l',
'PSO > Device and Shell Modifications > Shell Modifications > Gait > gait_r',
'PSO > Components > Shell > shell-code_b',
'PSO > Components > Shell > shell-code_l',
'PSO > Components > Shell > shell-code_r',
'PSO > Components > Fill > fill-code_b',
'PSO > Components > Fill > fill-type_b',
'PSO > Components > Fill > fill-code_l',
'PSO > Components > Fill > fill-type_l',
'PSO > Components > Fill > fill-code_r',
'PSO > Components > Fill > fill-type_r',
'PSO > Components > Extension > ext-code_b',
'PSO > Components > Extension > ext-length_b',
'PSO > Components > Extension > ext-sp-code_b',
'PSO > Components > Extension > ext-code_l',
'PSO > Components > Extension > ext-length_l',
'PSO > Components > Extension > ext-sp-code_l',
'PSO > Components > Extension > ext-code_r',
'PSO > Components > Extension > ext-length_r',
'PSO > Components > Extension > ext-sp-code_r',
'PSO > Components > Top Cover > tc1-code_b',
'PSO > Components > Top Cover > tc1-length_b',
'PSO > Components > Top Cover > tc1-code_l',
'PSO > Components > Top Cover > tc1-length_l',
'PSO > Components > Top Cover > tc1-code_r',
'PSO > Components > Top Cover > tc1-length_r',
'PSO > Components > Top Cover > tc2-code_b',
'PSO > Components > Top Cover > tc2-length_b',
'PSO > Components > Top Cover > tc2-code_l',
'PSO > Components > Top Cover > tc2-length_l',
'PSO > Components > Top Cover > tc2-code_r',
'PSO > Components > Top Cover > tc2-length_r',
'PSO > Components > Top Cover > tc3-code_b',
'PSO > Components > Top Cover > tc3-length_b',
'PSO > Components > Top Cover > tc3-code_l',
'PSO > Components > Top Cover > tc3-length_l',
'PSO > Components > Top Cover > tc3-code_r',
'PSO > Components > Top Cover > tc3-length_r',
'PSO > Components > Bottom Cover > bc-code_b',
'PSO > Components > Bottom Cover > bc-length_b',
'PSO > Components > Bottom Cover > bc-code_l',
'PSO > Components > Bottom Cover > bc-length_l',
'PSO > Components > Bottom Cover > bc-code_r',
'PSO > Components > Bottom Cover > bc-length_r',
'PSO > Components > Rearfoot Post > rf-post-code_b',
'PSO > Components > Rearfoot Post > rf-post-type_b',
'PSO > Components > Rearfoot Post > rf-post-code_l',
'PSO > Components > Rearfoot Post > rf-post-type_l',
'PSO > Components > Rearfoot Post > rf-post-code_r',
'PSO > Components > Rearfoot Post > rf-post-type_r',
'PSO > Components > Strikeplate > strikeplate-code_b',
'PSO > Components > Strikeplate > strikeplate-code_l',
'PSO > Components > Strikeplate > strikeplate-code_r',
'PSO > Components > Forefoot Post > ff-post-code_b',
'PSO > Components > Forefoot Post > ff-post-type_b',
'PSO > Components > Forefoot Post > ff-post-sp-code_b',
'PSO > Components > Forefoot Post > ff-post-code_l',
'PSO > Components > Forefoot Post > ff-post-type_l',
'PSO > Components > Forefoot Post > ff-post-sp-code_l',
'PSO > Components > Forefoot Post > ff-post-code_r',
'PSO > Components > Forefoot Post > ff-post-type_r',
'PSO > Components > Forefoot Post > ff-post-sp-code_r',
'PSO > Components > Addition > add1-code_b',
'PSO > Components > Addition > add1-code_l',
'PSO > Components > Addition > add1-code_r',
'PSO > Components > Addition > add2-code_b',
'PSO > Components > Addition > add2-code_l',
'PSO > Components > Addition > add2-code_r',
'PSO > Components > Addition > add3-code_b',
'PSO > Components > Addition > add3-code_l',
'PSO > Components > Addition > add3-code_r',
'PSO > Components > Addition > heel-lift-code_b',
'PSO > Components > Addition > heel-lift-length_b',
'PSO > Components > Addition > heel-lift-sp-code_b',
'PSO > Components > Addition > heel-lift-code_l',
'PSO > Components > Addition > heel-lift-length_l',
'PSO > Components > Addition > heel-lift-sp-code_l',
'PSO > Components > Addition > heel-lift-code_r',
'PSO > Components > Addition > heel-lift-length_r',
'PSO > Components > Addition > heel-lift-sp-code_r',
'PSO > Posting and Cast Dressing > Order Specifications > Posting Position > posting-position_b',
'PSO > Posting and Cast Dressing > Order Specifications > Posting Position > posting-position_l',
'PSO > Posting and Cast Dressing > Order Specifications > Posting Position > posting-position_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Corrections Type > corr-type_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Corrections Type > corr-type_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Corrections Type > corr-type_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive-uom_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive-uom_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Skive > skive-uom_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever-uom_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever-uom_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Inversion/Eversion > inver-ever-uom_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle-uom_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle-uom_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Rearfoot Extrinsic Angle > rf-ex-angle-uom_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle-uom_b',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle-uom_l',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle_r',
'PSO > Posting and Cast Dressing > Digital Corrections > Forefoot Extrinsic Angle > ff-ex-angle-uom_r'
]


class Order:
    def __init__(self):
        # Creates the order structure
        self.tree = {}
        self.fields = copy.deepcopy(valid_fields)
        self._create_tree()

        # clear fields
        for field in self.fields:
            self.fields[field] = None

    def _create_tree(self):
        my_tree = {}
        for line in tree_lines:
            fields = line.split(">")
            clean_fields = [f.strip() for f in fields]
            parent = my_tree
            for f in clean_fields:
                if f not in parent:
                    parent[f] = {}
                parent = parent[f] # put pointer to child

        self.tree = my_tree
        # print(json.dumps(self.tree, indent=4))

#
# o = Order()
#
# o.fields['foot-to-scan'] = row[7].value
#
# # 'PSO > General Order Info > Foot Impression > Foot to Scan > foot-to-scan',
# o.tree['PSO']['General Order Info']['Foot Impression']['Foot to Scan']['foot-to-scan'] = "value"
# print o.tree['PSO']['General Order Info']  # in house work order display


#    def create_order(file):
#
#    def get_long_name
